### ISSUE TITLE
How to specify the datetime format for ros2 logs?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [ros2/rcl_logging#107]
I read https://docs.ros.org/en/foxy/Tutorials/Demos/Logging-and-logger-configuration.html#console-output-formatting but it doesn't mention how to specify the datetime format to be something else than seconds, is that possible?

**Comment by jrutgeer** [comment]
See my answer [here](https://robotics.stackexchange.com/a/105135/35117).

**Comment by Kaju-Bubanja** [comment]
Thank you very much for the pointers, with your help I could implement the desired functionality: https://github.com/ros2/rcutils/compare/humble...Kaju-Bubanja:rcutils:humble it is for sure not up to the standards to integrate it with ros2, but at least people can adapt it to their use case

**Comment by jrutgeer** [comment]
Interesting. Thanks for sharing!

**Comment by clalancette** [comment]
@Kaju-Bubanja If you'd be willing to open a pull request that targets the rcutils `rolling` branch, we could consider getting that in.

**Comment by Kaju-Bubanja** [comment]
My C knowledge is quite weak, so I think some things will be missing if I make a PR:
- error handling
- proper configuration (currently the datestring format is just hard coded)
- efficiency (I'm not sure my implementation is the most efficient one, memory and cpu wise)

I can open the PR and maybe somebody else could improve the above mentioned points. I think I will be able to get to it next week.

**Comment by Kaju-Bubanja** [comment]
@clalancette 
I did it: https://github.com/ros2/rcutils/pull/439
