### ISSUE TITLE
Support compiling rcl_logging_log4cxx with libc++

### ISSUE THREAD

**Issue by nburek** [ros2/rcl_logging#14]
If you attempt to build ROS2 with clang and libc++ you will run into build issues when linking the rcl package because it is unable to find the Log4cxx API's used by rcl_logging_log4cxx. This is likely due to the fact that the version of log4cxx that is used comes from an apt repository and is likely compiled using libstdc++. Since the log4cxx API's use std lib classes it is not able to resolve linking the classes from one std lib to the other.

**Comment by clalancette** [comment]
This one is no longer a problem since we removed log4cxx in #78.  So I'll close this.
