### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by Blast545** [ros2/rcl_logging#28]
This issue tracks the progression of packages in `rcl_logging` that have been deemed necessary for Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/rep-2004/rep-2004.rst). 

The packages slated for Quality Level 1 for ROS 2 Foxy are:
- rcl_logging_spdlog

Excluded for Quality Level 1 at this time:
- rcl_logging_log4cxx
- rcl_logging_noop

# Progress rcl_logging_spdlog:
* [x] Version Policy
    - `semver` according to the recommendation for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#versioning).
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Recommended guidelines for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#package-requirements)
* [x] API and ABI stability within a ROS distribution
* [x] Vulnerability Disclosure Policy

Documentation
* [x] Per-feature documentation. 
* [x] Per-item documentation in public API.
    - Docstrings, not hosted
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Checked with `ament_copyright`
* [x] Quality Declaration document

Testing:
* [x] System tests, which cover "features"
* [x] Tests covering public API
* [x] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage)
* [x] Performance tests: not currently available.
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rcutils (QL 2)
    - spdlog_vendor (QL 2) 
* [x] non-ROS dependencies are equivalent level 1
    - None

Platform Support
* [x] Supports all tier 1 platforms as described in [REP-2000](https://www.ros.org/reps/rep-2000.html#support-tiers)

Security

* [x] Vulnerability Disclosure Policy

**Comment by ahcorde** [comment]
Bump QD to level 3 and updated QD https://github.com/ros2/rcl_logging/pull/44

Udpated issue

**Comment by chapulina** [comment]
Reached level 1: https://github.com/ros2/rcl_logging/pull/66
