### ISSUE TITLE
Configure logging directory

### ISSUE THREAD

**Issue by jacobperron** [ros2/rcl_logging#50]
Currently, all logs are saved to the directory `~/.ros/log`, which is hardcoded in the following places:

https://github.com/ros2/rcl_logging/blob/07463919e1a791d7acf69d70f8f06a51b3115319/rcl_logging_log4cxx/src/rcl_logging_log4cxx/rcl_logging_log4cxx.cpp#L135

https://github.com/ros2/rcl_logging/blob/07463919e1a791d7acf69d70f8f06a51b3115319/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp#L101

https://github.com/ros2/launch/blob/e51484685387d4186358ad128d3a4232a5d06522/launch/launch/logging/__init__.py#L96

In ROS 1, we can change the directory logs are saved to by setting the [`ROS_HOME`](http://wiki.ros.org/ROS/EnvironmentVariables#ROS_HOME) and/or [`ROS_LOG_DIR`](http://wiki.ros.org/ROS/EnvironmentVariables#ROS_LOG_DIR) environment variables.
It would be nice to have a way to configure the directory in ROS 2. 

I think an environment variable is a convenient way for users to configure the logging directory, although I propose using a single environment variable instead of combining two (like in ROS 1).

**Comment by dirk-thomas** [comment]
> which is hardcoded in the following places:

And in `launch`: https://github.com/ros2/launch/blob/e51484685387d4186358ad128d3a4232a5d06522/launch/launch/logging/__init__.py#L96

> In ROS 1, we can change the directory logs are saved to by setting the ROS_HOME environment variable.

Actually [ROS_LOG_DIR](http://wiki.ros.org/ROS/EnvironmentVariables#ROS_LOG_DIR).

**Comment by jacobperron** [comment]
Thanks, I've updated the description.

**Comment by clalancette** [comment]
@jacobperron What do you think we should do with this ticket?  Assign to you?  Backlog?  Help wanted?

**Comment by jacobperron** [comment]
@christophebedard Good point. I like the idea of having env variables for both the ROS "home" directory and log directory.

> What do you think we should do with this ticket? Assign to you? Backlog? Help wanted?

I don't expect to get to this any time soon. It seems like a good help wanted ticket, if there are no strong objections to using an environment variable.

**Comment by christophebedard** [comment]
@jacobperron I can do it!

Just to confirm, I'll go with this (again, if there no strong objections):

* Use `$ROS2_LOG_DIR` if `ROS2_LOG_DIR` if set.
* Otherwise, use `$ROS2_HOME/log`, using `~/.ros` for `ROS2_HOME` if not set.

I can also apply the same logic to `launch`.

**Comment by jacobperron** [comment]
@christophebedard Thanks, sounds good to me!

**Comment by ivanpauno** [comment]
FYI (to everybody in the thread), the opened PRs are using `ROS_LOG_DIR` and `ROS_HOME` instead of `ROS2_*` (for consistency with other environment variable names, see [comment](https://github.com/ros2/rcl_logging/pull/53#discussion_r497031929)).

https://github.com/ros2/ros2_documentation/pull/882 documents how the feature work.
