### ISSUE TITLE
spdlog dependency shouldn't need to be exported

### ISSUE THREAD

**Issue by sloretz** [ros2/rcl_logging#58]
https://github.com/ros2/rcl_logging/blob/e2456ba634223eb64aec197da7923295b468df6b/rcl_logging_spdlog/CMakeLists.txt#L64

If I understand correctly there's no reason to `ament_export_dependencies(spdlog spdlog_vendor)`. This call makes downstream packages `find_package()` them, but downstream code shouldn't need to know about them at all in order to use this logging implementation. The `<exec_depend>spdlog*` is enough to make the spdlog libraries available at runtime.

@hidmic thoughts?

**Comment by sloretz** [comment]
IIUC `rcutils` and `rcl_logging_interface` don't need to be "exported" either.

**Comment by sloretz** [comment]
I think the `ament_cmake` export happens automatically too, it seems like the whole line could be deleted

**Comment by hidmic** [comment]
Agree with this. And the same applies to `log4cxx` in `rcl_logging_log4cxx`.
