### ISSUE TITLE
Failed to get logging directory, at /home/usr/ros2_foxy/src/ros2/rcl_logging/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp:84

### ISSUE THREAD

**Issue by Kaju-Bubanja** [ros2/rcl_logging#72]
I have a bit an unusual setup. I have a django daphne server which I start over supervisor like so: `command=/bin/bash -c 'source "$0" && exec "$@"' /home/usr/ros2_foxy/install/setup.bash /home/usr/app/bin/daphne -t 30 --access-log - --proxy-headers web.asgi:application`. I have a small client which controls my ros node using pythons ros2lifecycle.api and ros2param.api. For this I need to create a node to be able to use these apis. Now my client works if run from a normal python file: 

    rclpy.init()
    client = Client()

but when running these same two lines inside of a django view I get following error stack trace:

```
>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'rcutils_expand_user failed, at /home/usr/ros2_foxy/src/ros2/rcl_logging/rcl_logging_interface/src/logging_dir.c:81'

with this new error message:

  'Failed to get logging directory, at /home/usr/ros2_foxy/src/ros2/rcl_logging/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp:84'

rcutils_reset_error() should be called after error handling to avoid this.
<<<

Traceback (most recent call last):
  File "/home/usr/PycharmProjects/myapp-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/usr/PycharmProjects/myapp-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/usr/PycharmProjects/myapp-app/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/usr/PycharmProjects/myapp-app/myapp-ui/myapp_ui/myapp_web/myapp/views.py", line 51, in start_something
    start_something()
  File "/home/usr/PycharmProjects/myapp-app/myapp-ui/myapp_ui/myapp_web/myapp/views.py", line 227, in stop_something
    rclpy.init()
  File "/home/usr/ros2_foxy/install/rclpy/lib/python3.8/site-packages/rclpy/__init__.py", line 76, in init
    return context.init(args, domain_id=domain_id)
  File "/home/usr/ros2_foxy/install/rclpy/lib/python3.8/site-packages/rclpy/context.py", line 76, in init
    rclpy_implementation.rclpy_logging_configure(capsule)
_rclpy.RCLError: Failed to initialize logging: Failed to get logging directory, at /home/usr/ros2_foxy/src/ros2/rcl_logging/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp:84
```
Now it must have something to do with the environment, since it works in a normal python script. But how can I get this to work in my context? I think it's the last step to be able to control the lifecycle and config of nodes using a web interface which would be quite handy.

**Comment by christophebedard** [comment]
> 'rcutils_expand_user failed, at /home/usr/ros2_foxy/src/ros2/rcl_logging/rcl_logging_interface/src/logging_dir.c:81'

Seems like this is the issue. The main reason `rcutils_expand_user()` could fail is if `rcutils_get_home_dir()` fails because the `HOME` (or `USERPROFILE`) env var is not defined or defined but empty. 

Can you check to make sure the `HOME` environment variable is defined with this setup/environment?

**Comment by clalancette** [comment]
[rcutils_expand_user](https://github.com/ros2/rcutils/blob/d413e135d9d2a520f84b70ce3b0fd9625592ec50/src/filesystem.c#L208) can only fail in 4 ways:

1. If the initial path you passed in was NULL
2. If copying the string failed
3. If the HOME environment variable is not set
4. If it failed to allocate memory for the final string

Of these, the most likely to be a problem in your setup by far is that HOME is unset.  You should check to see if that is set in your django server.

**Comment by Kaju-Bubanja** [comment]
Shouldn't sourcing the ros setup.bash script set the HOME variable? I printed os.environ and get a bunch of ros defined variables like ros_version, ros_python_version, ament_stuff, colon_stuff, ros_localhost, ros_distro etc. How come home is not set, but running the source script and then starting python it is set? I'm afraid of setting it manually, because who know what other env vars are not set. Shouldn't source error when some can not be set?

**Comment by clalancette** [comment]
> Shouldn't sourcing the ros setup.bash script set the HOME variable?

No, that is not the responsibility of ROS.  That is the responsibility of things external to ROS.  Usually this is set by your shell (bash, etc).

> How come home is not set, but running the source script and then starting python it is set?

If you are running it from a shell, then it is your shell that is setting it.

In any case, this doesn't look like an issue with rcl_logging directly, so I'm going to close this out.  If you are still having problems, please open up a question at https://answers.ros.org.

**Comment by Kaju-Bubanja** [comment]
Thanks very much, that was the culprit. I wasn't aware what responsibility the shell has and what the ros source script. I will have to see what other things the shell does which I need to emulate.
