### ISSUE TITLE
Log file output buffered.

### ISSUE THREAD

**Issue by rshanor** [ros2/rcl_logging#94]
Hi,

It looks like log files are buffered. Is there any way to configure ROS to write to file with every log statement? I am trying to use https://vector.dev/docs/reference/configuration/sources/file/ to push ROS logs to loki, but the buffering is confusing.

Thank you,
Rick

**Comment by clalancette** [comment]
It's a bug in the current implementation.  See https://github.com/ros2/rcl_logging/pull/95 , where we are fixing this.

**Comment by rshanor** [comment]
@clalancette thank you for the info. Adding config file options would be great but pushing every 5 seconds works for me for now.
